//Player Rankings 
    //via https://www.reddit.com/r/fantasybball/comments/9in504/heres_a_spreadsheet_of_espns_projected_stats_and/
const playerRanks = {
    "1" : "Giannis Antetokounmpo",
    "2" : "James Harden",
    "3" : "Anthony Davis",
    "4" : "Karl-Anthony Towns",
    "5" : "LeBron James",
    "6" : "Kevin Durant",
    "7" : "Russell Westbrook",
    "8" : "Damian Lillard",
    "9" : "Nikola Jokic",
    "10" : "Stephen Curry",
    "11" : "Kyle Lowry",
    "12" : "Kawhi Leonard",
    "13" : "Ben Simmons",
    "14" : "Andre Drummond",
    "15" : "John Wall",
    "16" : "DeMar DeRozan",
    "17" : "Jimmy Butler",
    "18" : "Joel Embiid",
    "19" : "LaMarcus Aldridge",
    "20" : "Victor Oladipo",
    "21" : "Chris Paul",
    "22" : "Kemba Walker",
    "23" : "Donovan Mitchell",
    "24" : "Jrue Holiday",
    "25" : "Kevin Love",
    "26" : "Bradley Beal",
    "27" : "Paul George",
    "28" : "Kyrie Irving",
    "29" : "CJ McCollum",
    "30" : "Khris Middleton",
    "31" : "Draymond Green",
    "32" : "Marc Gasol",
    "33" : "DeAndre Jordan",
    "34" : "Devin Booker",
    "35" : "Lou Williams",
    "36" : "Clint Capela",
    "37" : "Goran Dragic",
    "38" : "Deandre Ayton",
    "39" : "Dwight Howard",
    "40" : "Ricky Rubio",
    "41" : "Julius Randle",
    "42" : "Blake Griffin",
    "43" : "John Collins",
    "44" : "Mike Conley",
    "45" : "Rudy Gobert",
    "46" : "Jayson Tatum",
    "47" : "Gordon Hayward",
    "48" : "Enes Kanter",
    "49" : "Tobias Harris",
    "50" : "Luka Doncic",
    "51" : "Lonzo Ball",
    "52" : "Al Horford",
    "53" : "Harrison Barnes",
    "54" : "Jonas Valanciunas",
    "55" : "Brandon Ingram",
    "56" : "Eric Bledsoe",
    "57" : "Klay Thompson",
    "58" : "Andrew Wiggins",
    "59" : "Jamal Murray",
    "60" : "Nikola Vucevic",
    "61" : "Paul Millsap",
    "62" : "Dennis Smith Jr.",
    "63" : "Trae Young",
    "64" : "Lauri Markkanen",
    "65" : "Will Barton",
    "66" : "Elfrid Payton",
    "67" : "De'Aaron Fox",
    "68" : "Willie Cauley-Stein",
    "69" : "Kyle Kuzma",
    "70" : "Myles Turner",
    "71" : "Zach LaVine",
    "72" : "Hassan Whiteside",
    "73" : "Otto Porter Jr.",
    "74" : "Trey Burke",
    "75" : "Reggie Jackson",
    "76" : "Aaron Gordon",
    "77" : "Jeff Teague",
    "78" : "Jordan Clarkson",
    "79" : "TJ Warren",
    "80" : "Jusuf Nurkic",
    "81" : "Dario Saric",
    "82" : "D'Angelo Russell",
    "83" : "Rondae Hollis-Jefferson",
    "84" : "Jabari Parker",
    "85" : "Nicolas Batum",
    "86" : "Kris Dunn",
    "87" : "Wendell Carter Jr.",
    "88" : "Steven Adams",
    "89" : "Dennis Schroder",
    "90" : "D.J. Augustin",
    "91" : "Jarrett Allen",
    "92" : "Marvin Bagley III",
    "93" : "James Johnson",
    "94" : "Gary Harris",
    "95" : "Jordan Bell",
    "96" : "Dejounte Murray",
    "97" : "Dwight Powell",
    "98" : "Derrick Favors",
    "99" : "Kevin Knox",
    "100" : "Jerami Grant",
    "101" : "Rodney Hood",
    "102" : "Tim Hardaway Jr.",
    "103" : "Jaylen Brown",
    "104" : "Collin Sexton",
    "105" : "Nikola Mirotic",
    "106" : "Taj Gibson",
    "107" : "Rudy Gay",
    "108" : "Zach Randolph",
    "109" : "Brook Lopez",
    "110" : "Josh Jackson",
    "111" : "Kyle Anderson",
    "112" : "Darren Collison",
    "113" : "Jeremy Lin",
    "114" : "Markelle Fultz",
    "115" : "Danilo Gallinari",
    "116" : "Carmelo Anthony",
    "117" : "Jeremy Lamb",
    "118" : "Isaiah Thomas",
    "119" : "Evan Fournier",
    "120" : "Josh Richardson",
    "121" : "Tyreke Evans",
    "122" : "Greg Monroe",
    "123" : "Joe Ingles",
    "124" : "Buddy Hield",
    "125" : "Domantas Sabonis",
    "126" : "J.J. Barea",
    "127" : "Jaren Jackson Jr.",
    "128" : "Luke Kennard",
    "129" : "Marcin Gortat",
    "130" : "Bogdan Bogdanovic",
    "131" : "Frank Ntilikina",
    "132" : "Tyler Johnson",
    "133" : "Mario Hezonja",
    "134" : "Markieff Morris",
    "135" : "Kelly Olynyk",
    "136" : "Bobby Portis",
    "137" : "Kent Bazemore",
    "138" : "Taurean Prince",
    "139" : "Malcolm Brogdon",
    "140" : "Montrezl Harrell",
    "141" : "Bojan Bogdanovic",
    "142" : "Caris LeVert",
    "143" : "Miles Bridges",
    "144" : "Jonathon Simmons",
    "145" : "Alex Len",
    "146" : "Thaddeus Young",
    "147" : "JJ Redick",
    "148" : "Kelly Oubre Jr.",
    "149" : "Eric Gordon",
    "150" : "Robert Covington",
    "151" : "George Hill",
    "152" : "DeMarre Carroll",
    "153" : "Spencer Dinwiddie",
    "154" : "Larry Nance Jr.",
    "155" : "Patrick Beverley",
    "156" : "Michael Beasley",
    "157" : "Serge Ibaka",
    "158" : "Elie Okobo",
    "159" : "Tristan Thompson",
    "160" : "Jakob Poeltl",
    "161" : "Michael Kidd-Gilchrist",
    "162" : "Dewayne Dedmon",
    "163" : "Bam Adebayo",
    "164" : "Rajon Rondo",
    "165" : "JaMychal Green",
    "166" : "Marvin Williams",
    "167" : "Mohamed Bamba",
    "168" : "Mason Plumlee",
    "169" : "Dion Waiters",
    "170" : "Kentavious Caldwell-Pope",
    "171" : "Pau Gasol",
    "172" : "Josh Hart",
    "173" : "Pascal Siakam",
    "174" : "Fred VanVleet",
    "175" : "Dwyane Wade",
    "176" : "Justise Winslow",
    "177" : "Shai Gilgeous-Alexander",
    "178" : "Allen Crabbe",
    "179" : "Al-Farouq Aminu",
    "180" : "Ryan Anderson",
    "181" : "Terry Rozier",
    "182" : "Marcus Smart",
    "183" : "JaVale McGee",
    "184" : "Malik Monk",
    "185" : "Dirk Nowitzki",
    "186" : "E'Twaun Moore",
    "187" : "Avery Bradley",
    "188" : "Cody Zeller",
    "189" : "Frank Kaminsky",
    "190" : "Jae Crowder",
    "191" : "Ish Smith",
    "192" : "Chandler Hutchison",
    "193" : "OG Anunoby",
    "194" : "Gorgui Dieng",
    "195" : "Nerlens Noel",
    "196" : "Andre Iguodala",
    "197" : "John Henson",
    "198" : "Wesley Matthews",
    "199" : "Lonnie Walker IV",
    "200" : "Jerian Grant",
    "201" : "Patty Mills",
    "202" : "Kyle O'Quinn",
    "203" : "Bismack Biyombo",
    "204" : "Shaquille Harrison",
    "205" : "Cory Joseph",
    "206" : "Evan Turner",
    "207" : "Denzel Valentine",
    "208" : "Trey Lyles",
    "209" : "Maurice Harkless",
    "210" : "Ersan Ilyasova",
    "211" : "Dante Exum",
    "212" : "Amir Johnson",
    "213" : "Delon Wright",
    "214" : "Kenneth Faried",
    "215" : "Aaron Holiday",
    "216" : "Mikal Bridges",
    "217" : "Marcus Morris",
    "218" : "Willy Hernangomez",
    "219" : "Brandon Knight",
    "220" : "Courtney Lee",
    "221" : "Troy Brown Jr.",
    "222" : "PJ Tucker",
    "223" : "David Nwaba",
    "224" : "Zaza Pachulia",
    "225" : "Jeff Green",
    "226" : "Marco Belinelli",
    "227" : "Kosta Koufos",
    "228" : "Skal Labissiere",
    "229" : "Trevor Ariza",
    "230" : "Shelvin Mack",
    "231" : "Stanley Johnson",
    "232" : "Robin Lopez",
    "233" : "Jonathan Isaac",
    "234" : "Austin Rivers",
    "235" : "Aron Baynes",
    "236" : "Lance Stephenson",
    "237" : "Ivica Zubac",
    "238" : "Kristaps Porzingis",
    "239" : "Justin Holiday",
    "240" : "Danny Green",
    "241" : "Dillon Brooks",
    "242" : "Mario Chalmers",
    "243" : "Wayne Selden",
    "244" : "Reggie Bullock",
    "245" : "Garrett Temple",
    "246" : "Wilson Chandler",
    "247" : "Jamal Crawford",
    "248" : "Jon Leuer",
    "249" : "Emmanuel Mudiay",
    "250" : "DeMarcus Cousins",
    "251" : "Gerald Green",
    "252" : "Kyle Korver",
    "253" : "T.J. McConnell",
    "254" : "Kevin Huerter",
    "255" : "Cameron Payne",
    "256" : "Davis Bertans",
    "257" : "Zach Collins",
    "258" : "Joe Harris",
    "259" : "Tyus Jones",
    "260" : "Ante Zizic",
    "261" : "Cedi Osman",
    "262" : "Tyler Ulis",
    "263" : "Shabazz Napier",
    "264" : "Thon Maker",
    "265" : "Seth Curry",
    "266" : "Tony Parker",
    "267" : "Milos Teodosic",
    "268" : "Marquese Chriss",
    "269" : "Donte DiVincenzo",
    "270" : "Doug McDermott",
    "271" : "Terrence Ross",
    "272" : "Trevor Booker",
    "273" : "Thabo Sefolosha",
    "274" : "Yogi Ferrell",
    "275" : "Ben McLemore",
    "276" : "Dzanan Musa",
    "277" : "Derrick Rose",
    "278" : "Tyrone Wallace",
    "279" : "Michael Porter Jr.",
    "280" : "Shaun Livingston",
    "281" : "Mike Muscala",
    "282" : "Anfernee Simons",
    "283" : "Robert Williams",
    "284" : "Wayne Ellington",
    "285" : "Nemanja Bjelica",
    "286" : "Devin Harris",
    "287" : "Patrick Patterson",
    "288" : "Michael Carter-Williams",
    "289" : "CJ Miles",
    "290" : "Anthony Tolliver",
    "291" : "Nick Young",
    "292" : "Vince Carter",
    "293" : "Mike Scott",
    "294" : "Luc Mbah a Moute",
    "295" : "Jalen Brunson",
    "296" : "Quincy Acy",
    "297" : "Dante Cunningham",
    "298" : "Omari Spellman",
    "299" : "Jahlil Okafor",
    "300" : "Corey Brewer",
    "301" : "Darius Miller",
    "302" : "Tony Snell",
    "303" : "Josh Okogie",
    "304" : "JR Smith",
    "305" : "Moritz Wagner",
    "306" : "Chandler Parsons",
    "307" : "Dragan Bender",
    "308" : "Harry Giles",
    "309" : "Zhaire Smith",
    "310" : "Miles Plumlee",
    "311" : "Ian Mahinmi",
    "312" : "Tyson Chandler",
    "313" : "Jacob Evans",
    "314" : "Pat Connaughton",
    "315" : "Ian Clark",
    "316" : "James Ennis III",
    "317" : "Joakim Noah",
    "318" : "Grayson Allen",
    "319" : "Andre Roberson",
    "320" : "Jerome Robinson",
    "321" : "Timofey Mozgov",
    "322" : "Tyler Zeller",
    "323" : "Isaiah Canaan",
    "324" : "Treveon Graham",
    "325" : "Emeka Okafor",
    "326" : "Wesley Johnson",
    "327" : "Landry Shamet",
    "328" : "Jose Calderon",
    "329" : "Tim Frazier",
    "330" : "Jevon Carter",
    "331" : "Keita Bates-Diop",
    "332" : "Ekpe Udoh",
    "333" : "Manu Ginobili",
    "334" : "David West",
    "335" : "Matthew Dellavedova",
    "336" : "MarShon Brooks",
    "337" : "Meyers Leonard",
    "338" : "Jonas Jerebko",
    "339" : "Salah Mejri",
    "340" : "Nene Hilario",
    "341" : "D.J. Wilson",
    "342" : "Alexis Ajinca",
    "343" : "Daniel Theis",
    "344" : "Quinn Cook",
    "345" : "Donatas Motiejunas",
    "346" : "Jarell Martin",
    "347" : "Tomas Satoransky",
    "348" : "Andrew Harrison",
    "349" : "Melvin Frazier Jr.",
    "350" : "Raymond Felton",
    "351" : "Jarrett Jack",
    "352" : "Troy Daniels",
    "353" : "Deyonta Davis",
    "354" : "Kevon Looney",
    "355" : "Damian Jones",
    "356" : "Jodie Meeks",
    "357" : "Justin Jackson",
    "358" : "Richaun Holmes",
    "359" : "Omri Casspi",
    "360" : "Norman Powell",
    "361" : "Alec Peters",
    "362" : "Malcolm Delaney",
    "363" : "Frank Mason III",
    "364" : "Channing Frye",
    "365" : "Cheick Diallo",
    "366" : "Cristiano Felicio",
    "367" : "Lance Thomas",
    "368" : "Sindarius Thornwell",
    "369" : "Lucas Nogueira",
    "370" : "Devonte' Graham",
    "371" : "Mitchell Robinson",
    "372" : "Gary Trent Jr.",
    "373" : "Khyri Thomas",
    "374" : "Isaac Bonga",
    "375" : "Rodions Kurucs",
    "376" : "Jameer Nelson",
    "377" : "Jarred Vanderbilt",
    "378" : "Bruce Brown",
    "379" : "Justin Jackson"
}

const playerNamesMasterList = [
    "Giannis Antetokounmpo",
    "James Harden",
    "Anthony Davis",
    "Karl-Anthony Towns",
    "LeBron James",
    "Kevin Durant",
    "Russell Westbrook",
    "Damian Lillard",
    "Nikola Jokic",
    "Stephen Curry",
    "Kyle Lowry",
    "Kawhi Leonard",
    "Ben Simmons",
    "Andre Drummond",
    "John Wall",
    "DeMar DeRozan",
    "Jimmy Butler",
    "Joel Embiid",
    "LaMarcus Aldridge",
    "Victor Oladipo",
    "Chris Paul",
    "Kemba Walker",
    "Donovan Mitchell",
    "Jrue Holiday",
    "Kevin Love",
    "Bradley Beal",
    "Paul George",
    "Kyrie Irving",
    "CJ McCollum",
    "Khris Middleton",
    "Draymond Green",
    "Marc Gasol",
    "DeAndre Jordan",
    "Devin Booker",
    "Lou Williams",
    "Clint Capela",
    "Goran Dragic",
    "Deandre Ayton",
    "Dwight Howard",
    "Ricky Rubio",
    "Julius Randle",
    "Blake Griffin",
    "John Collins",
    "Mike Conley",
    "Rudy Gobert",
    "Jayson Tatum",
    "Gordon Hayward",
    "Enes Kanter",
    "Tobias Harris",
    "Luka Doncic",
    "Lonzo Ball",
    "Al Horford",
    "Harrison Barnes",
    "Jonas Valanciunas",
    "Brandon Ingram",
    "Eric Bledsoe",
    "Klay Thompson",
    "Andrew Wiggins",
    "Jamal Murray",
    "Nikola Vucevic",
    "Paul Millsap",
    "Dennis Smith Jr.",
    "Trae Young",
    "Lauri Markkanen",
    "Will Barton",
    "Elfrid Payton",
    "De'Aaron Fox",
    "Willie Cauley-Stein",
    "Kyle Kuzma",
    "Myles Turner",
    "Zach LaVine",
    "Hassan Whiteside",
    "Otto Porter Jr.",
    "Trey Burke",
    "Reggie Jackson",
    "Aaron Gordon",
    "Jeff Teague",
    "Jordan Clarkson",
    "TJ Warren",
    "Jusuf Nurkic",
    "Dario Saric",
    "D'Angelo Russell",
    "Rondae Hollis-Jefferson",
    "Jabari Parker",
    "Nicolas Batum",
    "Kris Dunn",
    "Wendell Carter Jr.",
    "Steven Adams",
    "Dennis Schroder",
    "D.J. Augustin",
    "Jarrett Allen",
    "Marvin Bagley III",
    "James Johnson",
    "Gary Harris",
    "Jordan Bell",
    "Dejounte Murray",
    "Dwight Powell",
    "Derrick Favors",
    "Kevin Knox",
    "Jerami Grant",
    "Rodney Hood",
    "Tim Hardaway Jr.",
    "Jaylen Brown",
    "Collin Sexton",
    "Nikola Mirotic",
    "Taj Gibson",
    "Rudy Gay",
    "Zach Randolph",
    "Brook Lopez",
    "Josh Jackson",
    "Kyle Anderson",
    "Darren Collison",
    "Jeremy Lin",
    "Markelle Fultz",
    "Danilo Gallinari",
    "Carmelo Anthony",
    "Jeremy Lamb",
    "Isaiah Thomas",
    "Evan Fournier",
    "Josh Richardson",
    "Tyreke Evans",
    "Greg Monroe",
    "Joe Ingles",
    "Buddy Hield",
    "Domantas Sabonis",
    "J.J. Barea",
    "Jaren Jackson Jr.",
    "Luke Kennard",
    "Marcin Gortat",
    "Bogdan Bogdanovic",
    "Frank Ntilikina",
    "Tyler Johnson",
    "Mario Hezonja",
    "Markieff Morris",
    "Kelly Olynyk",
    "Bobby Portis",
    "Kent Bazemore",
    "Taurean Prince",
    "Malcolm Brogdon",
    "Montrezl Harrell",
    "Bojan Bogdanovic",
    "Caris LeVert",
    "Miles Bridges",
    "Jonathon Simmons",
    "Alex Len",
    "Thaddeus Young",
    "JJ Redick",
    "Kelly Oubre Jr.",
    "Eric Gordon",
    "Robert Covington",
    "George Hill",
    "DeMarre Carroll",
    "Spencer Dinwiddie",
    "Larry Nance Jr.",
    "Patrick Beverley",
    "Michael Beasley",
    "Serge Ibaka",
    "Elie Okobo",
    "Tristan Thompson",
    "Jakob Poeltl",
    "Michael Kidd-Gilchrist",
    "Dewayne Dedmon",
    "Bam Adebayo",
    "Rajon Rondo",
    "JaMychal Green",
    "Marvin Williams",
    "Mohamed Bamba",
    "Mason Plumlee",
    "Dion Waiters",
    "Kentavious Caldwell-Pope",
    "Pau Gasol",
    "Josh Hart",
    "Pascal Siakam",
    "Fred VanVleet",
    "Dwyane Wade",
    "Justise Winslow",
    "Shai Gilgeous-Alexander",
    "Allen Crabbe",
    "Al-Farouq Aminu",
    "Ryan Anderson",
    "Terry Rozier",
    "Marcus Smart",
    "JaVale McGee",
    "Malik Monk",
    "Dirk Nowitzki",
    "E'Twaun Moore",
    "Avery Bradley",
    "Cody Zeller",
    "Frank Kaminsky",
    "Jae Crowder",
    "Ish Smith",
    "Chandler Hutchison",
    "OG Anunoby",
    "Gorgui Dieng",
    "Nerlens Noel",
    "Andre Iguodala",
    "John Henson",
    "Wesley Matthews",
    "Lonnie Walker IV",
    "Jerian Grant",
    "Patty Mills",
    "Kyle O'Quinn",
    "Bismack Biyombo",
    "Shaquille Harrison",
    "Cory Joseph",
    "Evan Turner",
    "Denzel Valentine",
    "Trey Lyles",
    "Maurice Harkless",
    "Ersan Ilyasova",
    "Dante Exum",
    "Amir Johnson",
    "Delon Wright",
    "Kenneth Faried",
    "Aaron Holiday",
    "Mikal Bridges",
    "Marcus Morris",
    "Willy Hernangomez",
    "Brandon Knight",
    "Courtney Lee",
    "Troy Brown Jr.",
    "PJ Tucker",
    "David Nwaba",
    "Zaza Pachulia",
    "Jeff Green",
    "Marco Belinelli",
    "Kosta Koufos",
    "Skal Labissiere",
    "Trevor Ariza",
    "Shelvin Mack",
    "Stanley Johnson",
    "Robin Lopez",
    "Jonathan Isaac",
    "Austin Rivers",
    "Aron Baynes",
    "Lance Stephenson",
    "Ivica Zubac",
    "Kristaps Porzingis",
    "Justin Holiday",
    "Danny Green",
    "Dillon Brooks",
    "Mario Chalmers",
    "Wayne Selden",
    "Reggie Bullock",
    "Garrett Temple",
    "Wilson Chandler",
    "Jamal Crawford",
    "Jon Leuer",
    "Emmanuel Mudiay",
    "DeMarcus Cousins",
    "Gerald Green",
    "Kyle Korver",
    "T.J. McConnell",
    "Kevin Huerter",
    "Cameron Payne",
    "Davis Bertans",
    "Zach Collins",
    "Joe Harris",
    "Tyus Jones",
    "Ante Zizic",
    "Cedi Osman",
    "Tyler Ulis",
    "Shabazz Napier",
    "Thon Maker",
    "Seth Curry",
    "Tony Parker",
    "Milos Teodosic",
    "Marquese Chriss",
    "Donte DiVincenzo",
    "Doug McDermott",
    "Terrence Ross",
    "Trevor Booker",
    "Thabo Sefolosha",
    "Yogi Ferrell",
    "Ben McLemore",
    "Dzanan Musa",
    "Derrick Rose",
    "Tyrone Wallace",
    "Michael Porter Jr.",
    "Shaun Livingston",
    "Mike Muscala",
    "Anfernee Simons",
    "Robert Williams",
    "Wayne Ellington",
    "Nemanja Bjelica",
    "Devin Harris",
    "Patrick Patterson",
    "Michael Carter-Williams",
    "CJ Miles",
    "Anthony Tolliver",
    "Nick Young",
    "Vince Carter",
    "Mike Scott",
    "Luc Mbah a Moute",
    "Jalen Brunson",
    "Quincy Acy",
    "Dante Cunningham",
    "Omari Spellman",
    "Jahlil Okafor",
    "Corey Brewer",
    "Darius Miller",
    "Tony Snell",
    "Josh Okogie",
    "JR Smith",
    "Moritz Wagner",
    "Chandler Parsons",
    "Dragan Bender",
    "Harry Giles",
    "Zhaire Smith",
    "Miles Plumlee",
    "Ian Mahinmi",
    "Tyson Chandler",
    "Jacob Evans",
    "Pat Connaughton",
    "Ian Clark",
    "James Ennis III",
    "Joakim Noah",
    "Grayson Allen",
    "Andre Roberson",
    "Jerome Robinson",
    "Timofey Mozgov",
    "Tyler Zeller",
    "Isaiah Canaan",
    "Treveon Graham",
    "Emeka Okafor",
    "Wesley Johnson",
    "Landry Shamet",
    "Jose Calderon",
    "Tim Frazier",
    "Jevon Carter",
    "Keita Bates-Diop",
    "Ekpe Udoh",
    "Manu Ginobili",
    "David West",
    "Matthew Dellavedova",
    "MarShon Brooks",
    "Meyers Leonard",
    "Jonas Jerebko",
    "Salah Mejri",
    "Nene Hilario",
    "D.J. Wilson",
    "Alexis Ajinca",
    "Daniel Theis",
    "Quinn Cook",
    "Donatas Motiejunas",
    "Jarell Martin",
    "Tomas Satoransky",
    "Andrew Harrison",
    "Melvin Frazier Jr.",
    "Raymond Felton",
    "Jarrett Jack",
    "Troy Daniels",
    "Deyonta Davis",
    "Kevon Looney",
    "Damian Jones",
    "Jodie Meeks",
    "Justin Jackson",
    "Richaun Holmes",
    "Omri Casspi",
    "Norman Powell",
    "Alec Peters",
    "Malcolm Delaney",
    "Frank Mason III",
    "Channing Frye",
    "Cheick Diallo",
    "Cristiano Felicio",
    "Lance Thomas",
    "Sindarius Thornwell",
    "Lucas Nogueira",
    "Devonte' Graham",
    "Mitchell Robinson",
    "Gary Trent Jr.",
    "Khyri Thomas",
    "Isaac Bonga",
    "Rodions Kurucs",
    "Jameer Nelson",
    "Jarred Vanderbilt",
    "Bruce Brown",
    "Justin Jackson"
];

const allTeams = [
    {name: "Atlanta Hawks", id: 1, url: "img/teams/atl.png"},
    {name: "Boston Celtics", id: 2, url: "img/teams/bos.png"},
    {name: "Brooklyn Nets", id: 3, url: "img/teams/bkn.png"},
    {name: "Charlotte Hornets", id: 4, url: "img/teams/cha.png"},
    {name: "Chicago Bulls", id: 5, url: "img/teams/chi.png"},
    {name: "Cleveland Cavaliers ", id: 6, url: "img/teams/cle.png"},
    {name: "Detroit Pistons", id: 9, url: "img/teams/det.png"},
    {name: "Indiana Pacers", id: 12, url: "img/teams/ind.png"},
    {name: "Miami Heat", id: 16, url: "img/teams/mia.png"},
    {name: "Milwaukee Bucks", id: 17, url: "img/teams/mil.png"},
    {name: "New York Knicks", id: 20, url: "img/teams/nyk.png"},
    {name: "Orlanda Magic", id: 22, url: "img/teams/orl.png"},
    {name: "Philadelphia 76ers", id: 23, url: "img/teams/phi.png"},
    {name: "Toronto Raptors", id: 28, url: "img/teams/tor.png"},
    {name: "Washington Wizards", id: 30, url: "img/teams/was.png"},
    {name: "Dallas Mavericks", id: 7, url: "img/teams/dal.png"},
    {name: "Denver Nuggests", id: 8, url: "img/teams/den.png"},
    {name: "Golden State Warriors", id: 10, url: "img/teams/gsw.png"},
    {name: "Houston Rockets", id: 11, url: "img/teams/hou.png"},
    {name: "Los Angeles Clippers", id: 13, url: "img/teams/lac.png"},
    {name: "Los Angeles Lakers", id: 14, url: "img/teams/lal.png"},
    {name: "Memphis Grizzlies", id: 15, url: "img/teams/mem.png"},
    {name: "Minnesota Timberwolves", id: 18, url: "img/teams/min.png"},
    {name: "New Orleans Pelicans", id: 19, url: "img/teams/nop.png"},
    {name: "Oklahoma City Thunder", id: 21, url: "img/teams/okc.png"},
    {name: "Phoenix Suns", id: 24, url: "img/teams/phx.png"},
    {name: "Portland Trail Blazers", id: 25, url: "img/teams/por.png"},
    {name: "Sacramento Kings", id: 26, url: "img/teams/sac.png"},
    {name: "San Antonio Spurs", id: 27, url: "img/teams/sas.png"},
    {name: "Utah Jazz", id: 29, url: "img/teams/uta.png"}
]

// const westTeams = [
//     {name: "Dallas Mavericks", id: 7, url: "../img/teams/dal.png"},
//     {name: "Denver Nuggests", id: 8, url: "../img/teams/den.png"},
//     {name: "Golden State Warriors", id: 10, url: "../img/teams/gsw.png"},
//     {name: "Houston Rockets", id: 11, url: "../img/teams/hou.png"},
//     {name: "Los Angeles Clippers", id: 13, url: "../img/teams/lac.png"},
//     {name: "Los Angeles Lakers", id: 14, url: "../img/teams/lal.png"},
//     {name: "Memphis Grizzlies", id: 15, url: "../img/teams/mem.png"},
//     {name: "Minnesota Timberwolves", id: 18, url: "../img/teams/min.png"},
//     {name: "New Orleans Pelicans", id: 19, url: "../img/teams/nop.png"},
//     {name: "Oklahoma City Thunder", id: 21, url: "../img/teams/okc.png"},
//     {name: "Phoenix Suns", id: 24, url: "../img/teams/phx.png"},
//     {name: "Portland Trail Blazers", id: 25, url: "../img/teams/por.png"},
//     {name: "Sacramento Kings", id: 26, url: "../img/teams/sac.png"},
//     {name: "San Antonio Spurs", id: 27, url: "../img/teams/sas.png"},
//     {name: "Utah Jazz", id: 29, url: "../img/teams/uta.png"}
// ]